### ISSUE TITLE
Question on reputation 

### ISSUE THREAD

**Issue by jennijuju** [MVelascoWS/MinerDealer#1]
amazing work on the lending contract MVP!

i have a quick question -  according https://ethglobal.com/showcase/minerdealer-wmkqj - `A smart contract was developed to know the reputation of the miner`, there might be a miner reputation system/contract and i wasnt able to find it here yet, is there any place i can read more about the reputation system design?

**Comment by MVelascoWS** [comment]
Thank you @jennijuju for your interest! Sorry about the misunderstood, We left the description with our initial aspirations, but at the end, We didn't have time to implement a reputation system. We have some rough ideas, but We want to continue work on it with a complete actors integration in the FEVM.

**Comment by jennijuju** [comment]
> Thank you @jennijuju for your interest! Sorry about the misunderstood, We left the description with our initial aspirations, but at the end, We didn't have time to implement a reputation system. We have some rough ideas, but We want to continue work on it with a complete actors integration in the FEVM.

gotcha!  jfyi there is a project called [onchain.storage](https://filecoinproject.slack.com/archives/C03CJKWP2DR) is also looking at SP reputation smart contracts - in case you are interested!
